import test from "node:test";
import assert from "node:assert/strict";

process.env.LMS_RP2B1_SUPABASE_STUB = "1";
process.env.SUPABASE_URL = "https://v5-test.invalid";
process.env.SUPABASE_SERVICE_ROLE_KEY = "v5-test-only";
process.env.V5_FIXTURE_MODE = "1";

const repo = await import("../../utils/v5/repository.js");
const { createFixtureState } = await import("../../utils/v5/fixtures.js");
const admin = { email: "admin@example.test" };
function reset() { globalThis.__LMS_V5_FIXTURE_STATE__ = createFixtureState(); }

test("feature flag fixture channel is enabled", async () => { reset(); assert.equal((await repo.getEnabledChannel("v5-co-ban")).course_slug, "v5-co-ban"); });
test("unknown channel falls back with v5_not_enabled", async () => { reset(); await assert.rejects(() => repo.getEnabledChannel("legacy"), { code: "v5_not_enabled" }); });
test("kill switch blocks V5", async () => { reset(); process.env.V5_GLOBAL_KILL_SWITCH = "1"; await assert.rejects(() => repo.getEnabledChannel("v5-co-ban"), { code: "v5_disabled" }); delete process.env.V5_GLOBAL_KILL_SWITCH; });
test("large fixture page uses cursor limit", async () => { reset(); const channel = await repo.getEnabledChannel("v5-feed-lon"); const page = await repo.listPosts(channel.id, { limit: 24 }); assert.equal(page.rows.length, 24); assert.equal(page.rows[0].sequence_no, 120); });
test("create draft writes audit", async () => { reset(); const channel = await repo.getEnabledChannel("v5-co-ban"); const post = await repo.createPost({ admin, input: { channel_id: channel.id, post_type: "text", body_text: "Xin chào", media: [] }, idempotencyKey: "create-key-001" }); assert.equal(post.status, "draft"); assert.equal(globalThis.__LMS_V5_FIXTURE_STATE__.audits.length, 1); });
test("create idempotency returns same post", async () => { reset(); const channel = await repo.getEnabledChannel("v5-co-ban"); const args = { admin, input: { channel_id: channel.id, post_type: "text", body_text: "Xin chào", media: [] }, idempotencyKey: "create-key-002" }; assert.equal((await repo.createPost(args)).id, (await repo.createPost(args)).id); });
test("idempotency conflict rejects changed request", async () => { reset(); const channel = await repo.getEnabledChannel("v5-co-ban"); await repo.createPost({ admin, input: { channel_id: channel.id, post_type: "text", body_text: "A", media: [] }, idempotencyKey: "same-key-003" }); await assert.rejects(() => repo.createPost({ admin, input: { channel_id: channel.id, post_type: "text", body_text: "B", media: [] }, idempotencyKey: "same-key-003" }), { code: "idempotency_conflict" }); });
test("publish transition writes version and published time", async () => { reset(); const channel = await repo.getEnabledChannel("v5-co-ban"); const draft = await repo.createPost({ admin, input: { channel_id: channel.id, post_type: "text", body_text: "A", media: [] }, idempotencyKey: "create-key-004" }); const post = await repo.mutatePost({ admin, postId: draft.id, action: "publish", idempotencyKey: "publish-key-004" }); assert.equal(post.status, "published"); assert.ok(post.published_at); assert.equal((await repo.postVersions(post.id)).length, 1); });
test("soft delete keeps post and media", async () => { reset(); const original = globalThis.__LMS_V5_FIXTURE_STATE__.posts.find((p) => p.media.length); const mediaCount = original.media.length; await repo.mutatePost({ admin, postId: original.id, action: "delete", idempotencyKey: "delete-key-001" }); assert.equal(original.status, "deleted"); assert.equal(original.media.length, mediaCount); });
test("restore soft-deleted post to draft", async () => { reset(); const post = globalThis.__LMS_V5_FIXTURE_STATE__.posts[0]; await repo.mutatePost({ admin, postId: post.id, action: "delete", idempotencyKey: "delete-key-002" }); await repo.mutatePost({ admin, postId: post.id, action: "restore", input: { restore_status: "draft" }, idempotencyKey: "restore-key-002" }); assert.equal(post.status, "draft"); assert.equal(post.deleted_at, null); });
test("duplicate creates independent draft", async () => { reset(); const post = globalThis.__LMS_V5_FIXTURE_STATE__.posts[0]; const clone = await repo.mutatePost({ admin, postId: post.id, action: "duplicate", idempotencyKey: "duplicate-key-1" }); assert.notEqual(clone.id, post.id); assert.equal(clone.status, "draft"); });
test("seen is idempotent by identity and post", async () => { reset(); const post = globalThis.__LMS_V5_FIXTURE_STATE__.posts[0]; const identity = { email: "student@example.test", studentId: null }; await repo.recordRead({ identity, post }); await repo.recordRead({ identity, post }); assert.equal(globalThis.__LMS_V5_FIXTURE_STATE__.reads.length, 1); });
test("completion is idempotent and records source", async () => { reset(); const post = globalThis.__LMS_V5_FIXTURE_STATE__.posts[0]; const identity = { email: "student@example.test", studentId: null }; await repo.recordRead({ identity, post, completed: true, completionSource: "manual_complete" }); const row = await repo.recordRead({ identity, post, completed: true, completionSource: "manual_complete" }); assert.equal(row.progress_percent, 100); assert.equal(row.completion_source, "manual_complete"); });
test("channel read state never moves backward", async () => { reset(); const channel = await repo.getEnabledChannel("v5-co-ban"); const identity = { email: "student@example.test" }; await repo.recordChannelRead({ identity, channelId: channel.id, sequence: 10 }); const row = await repo.recordChannelRead({ identity, channelId: channel.id, sequence: 5 }); assert.equal(row.last_read_sequence, 10); });
test("upload rejects oversized image", async () => { reset(); await assert.rejects(() => repo.initUpload({ admin, input: { media_type: "image", file_size: 21 * 1024 * 1024 } }), { code: "file_size_rejected" }); });
test("upload init returns direct fixture authorization without secret", async () => { reset(); const result = await repo.initUpload({ admin, input: { media_type: "image", file_size: 1024, mime_type: "image/png" } }); assert.equal(result.direct_upload, true); assert.equal(JSON.stringify(result).includes("service_role"), false); });
test("upload completion verifies ownership", async () => { reset(); const result = await repo.initUpload({ admin, input: { media_type: "image", file_size: 1024 } }); await assert.rejects(() => repo.finishUpload({ admin: { email: "other@example.test" }, uploadId: result.upload_id, action: "complete", input: {} }), { code: "upload_not_found" }); });
test("migration preview explicitly reports no production write", () => { reset(); assert.equal(repo.fixtureMigrationPreview().production_write, false); });
test("rollout zero is always fallback", () => assert.equal(repo.rolloutEligible({ course_slug: "a", rollout_percent: 0 }, "student@example.test"), false));
test("rollout one hundred always enables", () => assert.equal(repo.rolloutEligible({ course_slug: "a", rollout_percent: 100 }, ""), true));
test("rollout bucketing is deterministic per server identity", () => { const setting = { course_slug: "a", rollout_percent: 37 }; assert.equal(repo.rolloutEligible(setting, "student@example.test"), repo.rolloutEligible(setting, "student@example.test")); });
